"""AI-generated content disclaimers for draft and approved reports.

Disclaimers do not replace Guard, citation, or human-approval controls.
This module is Demo-grade governance disclosure, not an SFC certification claim.
"""
from __future__ import annotations

from typing import Any

DISCLAIMER_VERSION = "ai-research-disclaimer-v1"

_DISCLAIMERS: dict[str, str] = {
    "en": (
        "This report is AI-assisted research material generated by AlphaPilot from "
        "public market data and documents. It is not investment advice and is not an "
        "SFC compliance certification. Outputs may contain errors or omissions and "
        "remain subject to human review and approval before publication."
    ),
    "zh-Hans": (
        "本报告为 AlphaPilot 基于公开市场数据与文档自动生成的 AI 辅助研究材料，"
        "不构成任何形式的投资建议，也不是 SFC 合规认证。"
        "内容可能存在事实性错误或遗漏，发布前仍须完成人工审核和批准。"
    ),
    "yue": (
        "本報告係 AlphaPilot 基於公開市場數據同文檔自動生成嘅 AI 輔助研究材料，"
        "唔構成任何形式嘅投資建議，亦唔係 SFC 合規認證。"
        "內容可能有事實錯誤或者遺漏，發布前仍然要完成人工審核同批准。"
    ),
}


def normalize_disclaimer_language(language: str | None) -> str:
    """Map request/UI language tags onto supported disclaimer locales."""
    raw = (language or "").strip().lower().replace("_", "-")
    if not raw:
        return "en"
    if raw in {"yue", "zh-hk", "zh-hant", "zh-hant-hk", "zh-tw"}:
        return "yue"
    if raw.startswith("zh"):
        return "zh-Hans"
    if raw.startswith("en"):
        return "en"
    return "en"


def get_ai_disclaimer(language: str | None = "en") -> str:
    """Return the canonical AI research disclaimer for a language."""
    key = normalize_disclaimer_language(language)
    return _DISCLAIMERS.get(key) or _DISCLAIMERS["en"]


def get_disclaimer_payload(language: str | None = "en") -> dict[str, str]:
    """Return versioned disclaimer fields for API/export payloads."""
    return {
        "disclaimer": get_ai_disclaimer(language),
        "disclaimer_version": DISCLAIMER_VERSION,
    }


def attach_disclaimer_fields(
    payload: dict[str, Any] | None,
    language: str | None = "en",
) -> dict[str, Any]:
    """Copy a payload and attach versioned disclaimer fields."""
    result = dict(payload or {})
    result.update(get_disclaimer_payload(language))
    return result
